import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/siteUrl";

/**
 * /robots.txt
 *
 * Generated by Next rather than kept as a static file in /public so the host
 * always matches NEXT_PUBLIC_SITE_URL — a sitemap line pointing at the wrong
 * origin is silently ignored by crawlers, which is a hard problem to notice.
 *
 * Disallow vs noindex — these are not interchangeable, and mixing them up is
 * the classic way to leave a page indexed forever:
 *
 *   Disallow stops the crawl. The URL can still be indexed as a bare link if
 *   something points at it, because the crawler never fetches the page and so
 *   never sees any directive on it.
 *
 *   noindex removes it from the index, but ONLY if the crawler is allowed to
 *   fetch the page and read the tag.
 *
 * So anything linked from the site is left crawlable and carries `noindex` in
 * its own metadata instead:
 *   /login, /signup, /forgot-password  -> app/(auth)/layout.tsx
 *   /dashboard                         -> app/(site)/dashboard/page.tsx
 *
 * Disallow is reserved for what is neither linked nor useful to fetch:
 *   /admin, /api  staff-only and machine endpoints; nothing to index, and no
 *                 public link, so there is nothing to de-index.
 *   /sip/         per-user share links.
 *   *​/terminal    the TradingView chart view — an interactive widget with no
 *                 crawlable content of its own.
 *   /_next/       framework internals; crawling them only wastes budget.
 *
 * /markets/<symbol> stays fully crawlable (it is linked from /markets) but is
 * kept out of the sitemap; see app/sitemap.ts for why.
 *
 * No crawl-delay: Google ignores it and these pages are cheap to serve.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [
          "/admin",
          "/admin/",
          "/api/",
          "/sip/",
          "/markets/*/terminal",
          "/_next/",
        ],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
